### ISSUE TITLE
Look into using Docker for a LAMP stack

### ISSUE THREAD

**Issue by kenfehling** [SBUtltmedia/brainPicker#4]
- http://docker.com
- http://rancher.com/rancher-os

**Comment by SBUtltmedia** [comment]
Docker uses VirtualBox which is a pain to use with shared folders. [VMWare Fusion](https://stonybrook.onthehub.com/WebStore/OfferingDetails.aspx?o=a634ba62-0657-e511-9410-b8ca3a5db7a1)?

**Comment by SBUtltmedia** [comment]
Also [boot2docker](http://boot2docker.io) is another choice for a Docker OS
